// <auto-generated />
using System;
using LayoutManager.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LayoutManager.Model.Migrations
{
    [DbContext(typeof(LayoutManagerContext))]
    [Migration("20190708052828_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("LayoutManager.Model.Layout", b =>
                {
                    b.Property<int>("LayoutId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("LayoutId");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("LayoutManager.Model.Process", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Arguments");

                    b.Property<int>("Height");

                    b.Property<int?>("LayoutId");

                    b.Property<int>("Left");

                    b.Property<int>("LocationURL");

                    b.Property<int>("Path");

                    b.Property<int>("ProcessName");

                    b.Property<int>("Top");

                    b.Property<int>("Width");

                    b.HasKey("ProcessId");

                    b.HasIndex("LayoutId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("LayoutManager.Model.Process", b =>
                {
                    b.HasOne("LayoutManager.Model.Layout")
                        .WithMany("Posts")
                        .HasForeignKey("LayoutId");
                });
#pragma warning restore 612, 618
        }
    }
}
